VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  # use package caching if available
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end  
  
  config.vm.network "forwarded_port", guest: 3306, host: 3307
  config.vm.network "private_network", ip: "192.168.33.100"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
  end

  # to update the package repository index
  config.vm.provision "shell", inline: "apt-get update"

  # install Puppet modules if needed
  config.vm.provision "shell", path: "install-modules.sh"

  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "../infrastructure/puppet/manifests"
    puppet.module_path    = "modules_ext"
    puppet.manifest_file  = "app.pp"
  end

end
